networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
  web:
    image: web:v1
    container_name: web
